# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "antapi"
	LogPath     = "../../logs/antapi/server"

# Logger.
[logger]
    Path        = "../../logs/antapi"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[db]
    # upper支持的数据库：cockroachdb/mongo/mssql/mysql/postgresql/ql/sqlite
    Driver = "mysql"
    Link = "mysql:root:12345678@tcp(127.0.0.1:3306)/antapi"
    [db.logger]
        Path   = "../../logs/antapi/database"
        Level  = "all"
        Stdout = true