# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "antapi"
	LogPath     = "../../logs/antapi/server"

# Logger.
[logger]
    Path        = "../../logs/antapi"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    [database.logger]
        Path   = "../../logs/antapi/sql"
        Level  = "all"
        Stdout = true
    [database.default]
        # mysql/pgsql/mssql/sqlite/oracle
        Type   = "mysql"
        Link   = "mysql:root:12345678@tcp(127.0.0.1:3306)/antapi"
        Debug  = true